# Generated by Django 6.0 on 2025-12-20 11:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], db_index=True, max_length=10)),
                ('height_cm', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(250)])),
                ('weight_kg', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students_app.department')),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students_app.hobby')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StudentMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_course', models.BooleanField(default=False)),
                ('mark_10th', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mark_12th', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('college_mark', models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('daily_studying_time', models.CharField(choices=[('0-30m', '0 - 30 minutes'), ('30-60m', '30 - 60 minutes'), ('1-2h', '1 - 2 hours'), ('2-3h', '2 - 3 hours'), ('3-4h', '3 - 4 hours'), ('>4h', 'More than 4 hours')], max_length=20)),
                ('prefer_to_study_in', models.CharField(choices=[('Morning', 'Morning'), ('Night', 'Night'), ('Anytime', 'Anytime')], max_length=10)),
                ('salary_expectation', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)])),
                ('likes_degree', models.BooleanField(default=False)),
                ('willingness_percent', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('social_media_video', models.CharField(choices=[('0m', '0 minutes'), ('1-30m', '1 - 30 minutes'), ('30-60m', '30 - 60 minutes'), ('60-90m', '1 - 1.5 hour'), ('90-120m', '1.5 - 2 hour'), ('>2h', 'More than 2 hour')], max_length=20)),
                ('travelling_time', models.CharField(choices=[('0-30m', '0 - 30 minutes'), ('30-60m', '30 - 60 minutes'), ('60-90m', '1 - 1.5 hour'), ('90-120m', '1.5 - 2 hour'), ('120-150m', '2 - 2.5 hour'), ('150-180m', '2.5 - 3 hour'), ('>3h', 'More than 3 hour')], max_length=20)),
                ('stress_level', models.CharField(choices=[('Good', 'Good'), ('Fabulous', 'Fabulous'), ('Bad', 'Bad'), ('Awful', 'Awful')], db_index=True, max_length=20)),
                ('financial_status', models.CharField(choices=[('Awful', 'Awful'), ('Bad', 'Bad'), ('Good', 'Good'), ('Fabulous', 'Fabulous')], db_index=True, max_length=10)),
                ('part_time_job', models.BooleanField(default=False)),
                ('study_minutes', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)])),
                ('social_minutes', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)])),
                ('travel_minutes', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1440)])),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='students_app.student')),
            ],
            options={
                'ordering': ['student__id'],
            },
        ),
    ]
